### ISSUE TITLE
Проверка лабораторной работы 4

### ISSUE THREAD

**Issue by dragoblued** [dragoblued/lab_4#1]
Выполнила:
Табаева Н.А.

To:  @evgeny-p

**Comment by evgeny-p** [comment]
После клонирования репозитория команда `make` завершается с ошибкой:

```
$ make
gcc -c src/main.c -o obj/main.o
Assembler messages:
Fatal error: can't create obj/main.o: No such file or directory
```
Исправить можно созданием директорий из правил мейкфайла.

Небольшие доработки:

1. Заголовочный файл нужно подключать в соответствующий ему файл реализации. Подробнее описано [здесь](https://github.com/evgerher/Make/issues/1#issuecomment-197679513).
1. В файле `fun.c` незачем подключать `stdio.h`.
1. В файле `main.c` незачем подключать `string.h`.
1. Компилировать нужно с опцией `-Wall`.
1. Диагностические сообщения в функции `main` находятся в альтернативных ветках, но по своему смыслу означают одно и то же.

Форматирование:

1. Предлагаю в `main.c` строки 11−12 разделить на 4 для улучшения читаемости.
1. У функции `check_symbol` фигурная скобка с новой строки, у функции `main` на той же, что и заголовок. Если оставлять второй вариант, то добавить пробел перед фигурной скобкой.
1. `fun.c:8` слишком много пробелов перед открывающей фигурной скобкой, достаточно одного.

В последующих работах следует выбирать менее общие заголовки коммитов. По такой истории сложно понять смысл изменений:
```
*
|\  
| * 750e4f4 Change Makefile
| * 244097f Change fun.h
| * c0f3d96 Change main.c
| * 876bd3a Change fun.c
|/ 
*
```

**Comment by dragoblued** [comment]
Здравствуйте. Отредактировала.

**Comment by evgeny-p** [comment]
Приложение не компилируется.
